# Generated by Django 3.0.6 on 2023-01-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_App', '0004_auto_20230102_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuesModel',
        ),
        migrations.DeleteModel(
            name='QuesModelTwo',
        ),
    ]
