# Generated by Django 3.0.6 on 2023-01-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_App', '0006_quesmodel_quesmodeltwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_questions', models.CharField(max_length=200)),
                ('correct', models.CharField(max_length=200)),
                ('incorrect', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=200)),
                ('percentage', models.CharField(max_length=200)),
            ],
        ),
    ]
