# Generated by Django 3.0.6 on 2023-01-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_App', '0009_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='sl_no',
            field=models.IntegerField(),
        ),
    ]
