# Generated by Django 3.0.6 on 2023-01-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_App', '0010_auto_20230105_0601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
