# Generated by Django 3.0.6 on 2023-01-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_App', '0011_delete_leaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('quiz_name', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=200)),
                ('correct', models.CharField(max_length=200)),
                ('incorrect', models.CharField(max_length=200)),
                ('percentage', models.CharField(max_length=200)),
            ],
        ),
    ]
