# Generated by Django 3.0.6 on 2023-01-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_App', '0012_leaderboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
